dashboard:
    path:     /
    defaults:
        _controller: 'CTIC\App\Dashboard\Infrastructure\DashboardController'
        _controller_method: 'indexAction'
        _controller_create: 'CTIC\App\Dashboard\Application\CreateDashboardController'

login:
    path:     /login
    defaults:
        _controller: 'CTIC\App\User\Infrastructure\LoginController'
        _controller_method: 'loginAction'
        _controller_create: 'CTIC\App\User\Application\CreateLoginController'

logout:
    path:     /logout
    defaults:
        _controller: 'CTIC\App\User\Infrastructure\LoginController'
        _controller_method: 'logoutAction'
        _controller_create: 'CTIC\App\User\Application\CreateLoginController'

#Warehouse

GET_almacenes_listado:
    path:     /almacenes/listado
    defaults:
        _controller: 'CTIC\Warehouse\Warehouse\Infrastructure\WarehouseController'
        _controller_method: 'indexAction'
        _controller_create: 'CTIC\Warehouse\Warehouse\Application\CreateWarehouseController'

GET_almacenes_mostrar:
    path:     /almacenes/mostrar/{id}
    defaults:
        _controller: 'CTIC\Warehouse\Warehouse\Infrastructure\WarehouseController'
        _controller_method: 'showAction'
        _controller_create: 'CTIC\Warehouse\Warehouse\Application\CreateWarehouseController'

GET_almacenes_crear:
    path:     /almacenes/crear
    methods:  [GET, POST]
    defaults:
        _controller: 'CTIC\Warehouse\Warehouse\Infrastructure\WarehouseController'
        _controller_method: 'createAction'
        _controller_create: 'CTIC\Warehouse\Warehouse\Application\CreateWarehouseController'

GET_almacenes_modificar:
    path:     /almacenes/modificar/{id}
    methods:  [GET, POST]
    defaults:
        _controller: 'CTIC\Warehouse\Warehouse\Infrastructure\WarehouseController'
        _controller_method: 'updateAction'
        _controller_create: 'CTIC\Warehouse\Warehouse\Application\CreateWarehouseController'

POST_almacenes_eliminar:
    path:     /almacenes/eliminar/{id}
    methods:  [POST]
    defaults:
        _controller: 'CTIC\Warehouse\Warehouse\Infrastructure\WarehouseController'
        _controller_method: 'deleteAction'
        _controller_create: 'CTIC\Warehouse\Warehouse\Application\CreateWarehouseController'

POST_almacenes_eliminargrupo:
    path:     /almacenes/eliminargrupo
    methods:  [POST]
    defaults:
        _controller: 'CTIC\Warehouse\Warehouse\Infrastructure\WarehouseController'
        _controller_method: 'bulkDeleteAction'
        _controller_create: 'CTIC\Warehouse\Warehouse\Application\CreateWarehouseController'

POST_almacenes_descargar:
    path:     /almacenes/descargar
    methods:  [POST]
    defaults:
        _controller: 'CTIC\Warehouse\Warehouse\Infrastructure\WarehouseController'
        _controller_method: 'downloadAction'
        _controller_create: 'CTIC\Warehouse\Warehouse\Application\CreateWarehouseController'
